enableFeaturePreview("VERSION_CATALOGS")
include (":app")
include(":core:ui")
include(":core:navigation")
include(":core:data:local:core")
include(":core:data:local:mediastore")
include(":core:data:server:core")
include(":core:data:server:cajunlyrics")
include(":core:data:server:chartlyrics")
include(":core:data:server:lololyrics")
include(":core:data:server:deezer")
include(":core:data:server:itunes")
include(":core:data:server:mediator")
include(":feature:library:track")
include(":feature:library:core")
include(":feature:library:album")
include(":feature:privacypolicy")
