enableFeaturePreview("VERSION_CATALOGS")
include (":app")
include(":data:local:core")
include(":data:local:mediastore")
include(":feature")
include(":feature:library")
include(":feature:library:track")
include(":feature:library:core")
include(":feature:library:album")
include(":data:server:core")
include(":data:server:cajunlyrics")
