enableFeaturePreview("VERSION_CATALOGS")
include (":app")
include(":data:local:core")
include(":data:local:mediastore")
include(":feature:library:track")
include(":feature:library:core")
include(":feature:library:album")
include(":data:server:core")
include(":data:server:cajunlyrics")
include(":data:server:chartlyrics")
include(":data:server:lololyrics")
include(":data:server:deezer")
include(":data:server:itunes")
include(":data:server:mediator")
include(":ui")
